Question no.1 :- Set the variable test1 to the string 'This is a test of the emergency text system,' and save test1 to a file named test.txt.

Answer no.1

In [ ]:
test1 = "This is a test of the emergency text system"
with open("test.txt",'w') as f:
    f.write(test1)
    print(test1)

This is a test of the emergency text system

Question no.2 :- Read the contents of the file test.txt into the variable test2. Is there a difference between test 1 and test 2?

Answer no.2

In [ ]:
with open("test.txt",'r') as f2:
    test2 = f2.read()
    print(test2)

This is a test of the emergency text system

~ There is no difference between test1 and test2.

Question no.3 :- Create a CSV file called books.csv by using these lines:

title,author,year

The Weirdstone of Brisingamen,Alan Garner,1960

Perdido Street Station,China Miéville,2000

Thud!,Terry Pratchett,2005

The Spellman Files,Lisa Lutz,2007

Small Gods,Terry Pratchett,1992

Answer no.3

In [ ]:
with open("books.csv",'w') as f3:
    f3.write('''title,author,year

The Weirdstone of Brisingamen,Alan Garner,1960

Perdido Street Station,China Miéville,2000

Thud!,Terry Pratchett,2005

The Spellman Files,Lisa Lutz,2007

Small Gods,Terry Pratchett,1992''')

Question no.4 :- Use the sqlite3 module to create a SQLite database called books.db, and a table called books with these fields: title (text), author (text), and year (integer).

Answer no.4

In [ ]:
import sqlite3
conn = sqlite3.connect('Booksdb.db')
cursor = conn.cursor()
sql = '''create table Books(
    title char(50), 
    author char(50), 
    year int)'''
cursor.execute(sql)
print("Table has been created") 
conn.commit()

Table has been created

Question no.5 :- Read books.csv and insert its data into the book table.

Answer no.5

In [ ]:
import pandas as pd
users = pd.read_csv('books.csv')
users.to_sql('Books',conn,if_exists='append',index=False)

Question no.6 :- Select and print the title column from the book table in alphabetical order.

Answer no.6

In [ ]:
cursor.execute('''select title from Books order by title asc''')
xf = pd.DataFrame(cursor.fetchall(),columns = ['title'])
xf

                           title
0         Perdido Street Station
1                     Small Gods
2             The Spellman Files
3  The Weirdstone of Brisingamen
4                          Thud!

Question no.7 :- From the book table, select and print all columns in the order of publication.

Answer no.7

In [ ]:
cursor.execute('''select * from Books group by year order by year asc''')
vf = pd.DataFrame(cursor.fetchall(), columns = ['title','author','year'])
vf

                           title           author  year
0  The Weirdstone of Brisingamen      Alan Garner  1960
1                     Small Gods  Terry Pratchett  1992
2         Perdido Street Station   China Miéville  2000
3                          Thud!  Terry Pratchett  2005
4             The Spellman Files        Lisa Lutz  2007

Question no.8 :- Use the sqlalchemy module to connect to the sqlite3 database books.db that you just made in exercise 6.

Answer no.8

In [ ]:
import sqlalchemy
db_Engine = sqlalchemy.create_engine('sqlite:///Booksdb.db')
rows = db_Engine.execute('select * from Books')
for i in rows:
    print(i)

('The Weirdstone of Brisingamen', 'Alan Garner', 1960)
('Perdido Street Station', 'China Miéville', 2000)
('Thud!', 'Terry Pratchett', 2005)
('The Spellman Files', 'Lisa Lutz', 2007)
('Small Gods', 'Terry Pratchett', 1992)

Question no.9 :- Install the Redis server and the Python redis library (pip install redis) on your computer. Create a Redis hash called test with the fields count (1) and name ('Fester Bestertester'). Print all the fields for test.

Answer no.9

In [ ]:
!pip install redis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting redis
  Downloading redis-4.5.1-py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.5/238.5 KB 6.3 MB/s eta 0:00:00
Collecting async-timeout>=4.0.2
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Installing collected packages: async-timeout, redis
Successfully installed async-timeout-4.0.2 redis-4.5.1

In [40]:
import redis
r = redis.StrictRedis(host='localhost',port=6379,db=0)
hash_name = "Test"
r.hset(hash_name, 1 ,'Fester Bestertester')
print(r.hgetall(hash_name))

Question no.10 :- Increment the count field of test and print it.

Answer no.10

In [ ]:
r.hincrby('Test','count', 3)