Question no.1 :- 

Create a function that takes a number as an argument and returns True or False depending on whether the number is symmetrical or not. A number is symmetrical when it is the same as its reverse.

Examples

is_symmetrical(7227) ➞ True

is_symmetrical(12567) ➞ False

is_symmetrical(44444444) ➞ True

is_symmetrical(9939) ➞ False

is_symmetrical(1112111) ➞ True

Answer no.1

In [10]:
def is_symmetrical(num):
    
    N = str(num).split()
    
    for i in N:
        if i[::] == i[::-1]:
            return True
        else:
            return False

is_symmetrical(77577)

True

Question no.2 :- 

Given a string of numbers separated by a comma and space, return the product of the numbers.

Examples

multiply_nums("2, 3") ➞ 6

multiply_nums("1, 2, 3, 4") ➞ 24

multiply_nums("54, 75, 453, 0") ➞ 0

multiply_nums("10, -2") ➞ -20

Answer no.2

In [32]:
def multiply_nums(b):

    nums = b.split(",") 
     
    new_list = []

    for i in nums:
        y = int(i)
        new_list.append(y)
    
    mul = 1 
    for ele in new_list:
        mul = mul*ele
    
    return mul

multiply_nums("10, 3, 2")

60

Question no.3 :- 

Create a function that squares every digit of a number.

Examples

square_digits(9119) ➞ 811181

square_digits(2483) ➞ 416649

square_digits(3212) ➞ 9414

Notes

The function receives an integer and must return an integer.

Answer no.3

In [55]:
def square_digits(number):

    n = ''
    for i in str(number):
        n = n + str((int(i))**2)
    return int(n) 

square_digits(555)

252525

Question no.4 :-

Create a function that sorts a list and removes all duplicate items from it.

Examples

setify([1, 3, 3, 5, 5]) ➞ [1, 3, 5]

setify([4, 4, 4, 4]) ➞ [4]

setify([5, 7, 8, 9, 10, 15]) ➞ [5, 7, 8, 9, 10, 15]

setify([3, 3, 3, 2, 1]) ➞ [1, 2, 3]

Answer no.4

In [60]:
def setify(list):

    return sorted(set(list)) 

setify([1,3,7,7,8,5,5,8,9,2])

[1, 2, 3, 5, 7, 8, 9]

Question no.5 :-

Create a function that returns the mean of all digits.

Examples

mean(42) ➞ 3

mean(12345) ➞ 3

mean(666) ➞ 6

Notes

The mean of all digits is the sum of digits / how many digits there are (e.g. mean of digits in 512 is (5+1+2)/3(number of digits) = 8/3=2).

The mean will always be an integer.

Answer no.5

In [74]:
def mean(digit):

    length = len(str(digit))
    sum = 0

    for i in str(digit):
        sum = sum + int(i)

    m = sum//length
    return m

mean(777)

7